language: python
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.5-dev"
- "nightly"
- "pypy"
install:
- pip install pip -U
- pip install .[develop]
script:
- py.test
- ./pylint.sh
notifications:
  slack:
    secure: DKG0Djbzwa091bbdEkli1xxcJQ6DRTqaF05KpLGSV3RJqvhjFJrhDYWBLtL9hPqIsIy+KN0eWILbdCxMyTETKLuo6c3UGUKyDTBp8mGWqdDjx1x7kIYRkoI94vhGoIVPIHnf/jXrJIUkkifH79CUKqIKaeh/3/DhF9DG5thjFt8UMbaa7jZTvbeS0UBUTR3QuOjfPjuKpetv/rcQa0CpjsDgfjvAlqzrm1u3wivVMUsBsMjasBkG8iz+3Iw3DPsIenkYhzUpQGEXNzxAhpF7DCzXvM4QwRlS1t875PMTJONiCsVE/5hGsqtxmsjrUSuz/A6DN/Onu6j4eIg3CQ3RNTLtRYT8knlHtPWCXv7BM3u9k3EjA4OSrc8OBKGfFnnX4j0WIPApIZIUVvf4/TV8A6qwkRzLEzBb/yPYMT3NjOSLpM5dr7CLewjo8eEj/YcZDGWuEGd2f1Q5rXIVYXbivhao649mbW4/PSD9jd7vo6CGeBasyduUl3DTzV3XH0XQiMzKcYH3OU93o1mWOF2AiLX78MFH7JcYaygAgwzbTjAejNsM2kkllv+yObIQYg9XPMTSvsVgdPzp2lbRbYy8DCM/7dU6Iz9Cn9S+1QvsVg5iWyOf8qeY3py7PlRXnJ+xowOLYEJiZFm96b0+bYyihHI+6qcvFB0VKm5fgX5cF5Y=
deploy:
  provider: pypi
  user: lemmons
  password:
    secure: l1jWB+BjBf0/oGjK+9nOHnVp1/KF+J7V1+s5DVbdXHFzCIi/Et5xjuevttmmFDkJ3UUtbU1XrHm2wnPBrxocZqkpcP1DAUd3GD7A6b4C8AU65C7T1MgfXbLR5qGNYC+K59DqLVTV0jOM8GwZ7MiL1YIfSSkpmZn/l+BK397wMSMnl3DuIg6rse8Y3WVE+E0zDOsF5Mqs0CzvPcpSeHykG6LDHqSxR9ZT1verJq5Sj07OoF43ppllbaJ/EhcUVuN0Me5mJEPCtKb2qz8gcPF4THzBjec3wjZrD9NAsm5ewGQZGwydtL7SxVbzeTM6RlM7M3yYrvxD9H3YEo8HjqBLNTINZHLI9FLJ4dpHevGUuFzIbzpG4Ip6GbQgS1llGg5FS68pdnEZWP22igywKPOIM1qWsqrv8HSzcNJ7SXcUCpH2tmMrmEfHETI7UBRtYN3CGIn4glpaRDNoOsLp9W8zox7toJmJ+f+o5K2HWmXZcmcPxYCje+p0T0A/wyKlClVtFzHTFpcwwecCmmJ0AB0OUnRQp8oCbW2tHL7oHvQXZ/rUWA4r4es9DjUCHuORhc0ygGXBFAE0pna3O94xMXbPw07LxFwPKINU1RyWHWFx+ZLdWmpjSpJ7dTH/p2EfMXVyLXEUp0NPvkHJBqWxgYJgzr/OA7kD6q5RVRfXazxSjJI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
    repo: Authentise/pytest-raises
